apiVersion: extensions/v1beta1  # API Version が古い
kind: Deployment
metadata:
  name: hello
spec:
  selector:
    matchLabels:
      run: hello
  template:
    metadata:
      labels:
        run: hello
    spec:
      containers:
      - image: nginx:1.17.3
        name: multi
        securityContext:  # privileged は禁止したい
          privileged: true