apiVersion: v1
#apiVersion: extensions/v1beta1 

kind: Pod
metadata:
  name: windows_host
spec:
  containers:
  - name: windows_host
    image: paulbouwer/hello-kubernetes:1.5
    ports:
    - containerPort: 8080
      protocol: tcp
    securityContext:
      allowPrivilegeEscalation: false
      windowsOptions:
        hostProcess: false
#  securityContext:
#    seccompProfile:
#      type: Unconfined
