apiVersion: v1
kind: Pod
metadata:
  name: windows_host
spec:
  hostIPC: false
  hostNetwork: false
  hostPID: false
  containers:
  - name: windows_host
    image: paulbouwer/hello-kubernetes:1.5
    ports:
    - containerPort: 8080
      protocol: tcp
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        add : 
          windowsOptions:
          hostProcess: false
  volumes:
  - name: hostpath-test
    hostPath:undefined
#      path: /etc

#  securityContext:
#    seccompProfile:
#      type: Unconfined
