apiVersion: v1
kind: Pod
metadata:
  name: windows_host
spec:
  hostIPC: false
  hostNetwork: false
  hostPID: false
  initContainers:
  - name: init01
    image: centos:latest
    ports: 
      hostPort: 8080

#    args:
#    - /bin/sh
#    - -c
#    - echo "test" > /test/index.html
  containers:
  - name: windows_host
    image: paulbouwer/hello-kubernetes:1.5
    ports:
    - containerPort: 80
      protocol: tcp
      hostPort : 8080
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        add : 
        - "NET_ADMIN"
      windowsOptions:
        hostProcess: false
#    volumeMounts: 
#    - name: test-pvc
#      mountPath: /data
#  volumes:
#  - name: hostpath-test
#    persistentVolumeClaim:
#      claimName: test-pvc
##    hostPath: 
#      path: \
 
#  securityContext:
#    seccompProfile:
#      type: Unconfined
