apiVersion: v1
kind: Pod
metadata:
  name: hello-apparmor
  annotations:
#    container.apparmor.security.beta.kubernetes.io/windows_host: lruntime/default
#    container.apparmor.security.beta.kubernetes.io/*: lruntime/default
#    container.apparmor.security.beta.kubernetes.io/*: test

spec:
  hostIPC: false
  hostNetwork: false
  hostPID: false

  ephemeralContainers:
  - name: windows_host
    image: paulbouwer/hello-kubernetes:1.5
    ports:
    - containerPort: 80
      protocol: tcp
#      hostPort: 8080
#      03 hostPort : 8080  ※エラー出現OK 5_access_to_host_ports.rego


  initContainers:
  - name: windows_host
    image: paulbouwer/hello-kubernetes:1.5
    ports:
    - containerPort: 80
      protocol: tcp
#      hostPort : 8080
#      02 hostPort : 8080  ※エラー出現OK 5_access_to_host_ports.rego

#spec.initContainers[*].securityContext.seLinuxOptions

  containers:
  - name: windows_host
    image: paulbouwer/hello-kubernetes:1.5
    ports:
    - containerPort: 80
      protocol: tcp
#      hostPort : 8080
#      01 hostPort : 8080  ※エラー出現OK 5_access_to_host_ports.rego

#spec.containers[*].securityContext.seLinuxOptions テストOK
    securityContext:
      windowsOptions:
        hostProcess: false
      seLinuxOptions: 
        type: container_t


  securityContext:
    windowsOptions:
      hostProcess: false
    seLinuxOptions: 
      type: container_t

#    allowPrivilegeEscalation: false
#    capabilities:
#      add : 
#      - "NET_ADMIN"

    
#    volumeMounts: 
#    - name: test-pvc
#      mountPath: /data
#  volumes:
#  - name: hostpath-test
#    persistentVolumeClaim:
#      claimName: test-pvc
##    hostPath: 
#      path: \
 
#  securityContext:
#    seccompProfile:
#      type: Unconfined
