apiVersion: v1
kind: Pod
metadata:
  name: windows_host
spec:
  hostIPC: false
  hostNetwork: false
  hostPID: false
  volumes:hostPath
  containers:
  - name: windows_host
    image: paulbouwer/hello-kubernetes:1.5
    ports:
    - containerPort: 8080
      protocol: tcp
    securityContext:
      allowPrivilegeEscalation: false
      windowsOptions:
        hostProcess: false
#  volumes:
#  - name: hostpath-sample
#    hostPath:
#      path: /etc
#      type: DirectoryOrCreate

#  securityContext:
#    seccompProfile:
#      type: Unconfined
