apiVersion: v1
kind: Pod
metadata:
  name: hello-apparmor
  annotations:
    container.apparmor.security.beta.kubernetes.io/runtime
spec:
  hostIPC: false
  hostNetwork: false
  hostPID: false

  ephemeralContainers:
  - name: windows_host
    image: paulbouwer/hello-kubernetes:1.5
    ports:
    - containerPort: 80
      protocol: tcp
#      hostPort: 8080
#      03 hostPort : 8080  ※エラー出現OK 5_access_to_host_ports.rego


  initContainers:
  - name: windows_host
    image: paulbouwer/hello-kubernetes:1.5
    ports:
    - containerPort: 80
      protocol: tcp
#      hostPort : 8080
#      02 hostPort : 8080  ※エラー出現OK 5_access_to_host_ports.rego

  containers:
  - name: windows_host
    image: paulbouwer/hello-kubernetes:1.5
    ports:
    - containerPort: 80
      protocol: tcp
#      hostPort : 8080
#      01 hostPort : 8080  ※エラー出現OK 5_access_to_host_ports.rego

    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        add : 
        - "NET_ADMIN"
      windowsOptions:
        hostProcess: false
#    volumeMounts: 
#    - name: test-pvc
#      mountPath: /data
#  volumes:
#  - name: hostpath-test
#    persistentVolumeClaim:
#      claimName: test-pvc
##    hostPath: 
#      path: \
 
#  securityContext:
#    seccompProfile:
#      type: Unconfined
