apiVersion: v1
kind: Pod
metadata:
  name: hello-apparmor
  annotations:
     container.apparmor.security.beta.kubernetes.io/*: lruntime/default
#    container.apparmor.security.beta.kubernetes.io/*: runtime/default3
#    container.apparmor.security.beta.kubernetes.io/*: test

spec:
  hostIPC: false
  hostNetwork: false
  hostPID: false

  ephemeralContainers:
  - name: windows_host
    image: paulbouwer/hello-kubernetes:1.5
    ports:
    - containerPort: 80
      protocol: tcp
#      hostPort: 8080
#      03 hostPort : 8080  ※エラー出現OK 5_access_to_host_ports.rego

#spec.ephemeralContainers[*].securityContext.seLinuxOptions.type
    securityContext:
      seLinuxOptions: 
        type: container_t
#spec.securityContext.seLinuxOptions.user
#        user: aaa

  initContainers:
  - name: windows_host
    image: paulbouwer/hello-kubernetes:1.5
    ports:
    - containerPort: 80
      protocol: tcp
#      hostPort : 8080
#      02 hostPort : 8080  ※エラー出現OK 5_access_to_host_ports.rego

  #spec.initContainers[*].securityContext.seLinuxOptions
    securityContext:
      windowsOptions:
        hostProcess: false
      seLinuxOptions: 
        type: container_t
#       role: testname 
#        user: user1

  containers:
  - name: windows_host
    image: paulbouwer/hello-kubernetes:1.5
    ports:
    - containerPort: 80
      protocol: tcp
          #      hostPort : 8080
          #      01 hostPort : 8080  ※エラー出現OK 5_access_to_host_ports.rego
    #spec.containers[*].securityContext.seLinuxOptions テストOK
    securityContext:
      capabilities:
        add:
        - AUDIT_WRITE
      windowsOptions: 
        hostProcess: false
      seLinuxOptions: 
#        role: testname 
#        user: user1
        type: container_t
#
      procMount: Default 

  securityContext:
    windowsOptions:
      hostProcess: false
#spec.securityContext.seLinuxOptions
    seLinuxOptions: 
      type: container_t

#spec.securityContext.sysctls
    sysctls:
    - name: net.ipv4.ip_local_port_rangeaa

#    allowPrivilegeEscalation: false
#    capabilities:
#      add : 
#      - "NET_ADMIN"

    
#    volumeMounts: 
#    - name: test-pvc
#      mountPath: /data
#  volumes:
#  - name: hostpath-test
#    persistentVolumeClaim:
#      claimName: test-pvc
##    hostPath: 
#      path: \
 
#  securityContext:
#    seccompProfile:
#      type: Unconfined
