name: conftest

on:
  push:
    branches:
      - develop/conftest
  pull_request:
    branches:
      - develop/conftest

#条件
jobs:
  import_policy:
    name: conf test
    runs-on: ubuntu-latest

    steps:
      - name: This repository
        uses: actions/checkout@v3
      
      - name: rego repository
        uses: actions/checkout@v3
        with:
          repository: ytakenouchi/ci-conftest
          path: policy
      - name: conf install
        run: |
          LATEST_VERSION=$(wget -O - "https://api.github.com/repos/open-policy-agent/conftest/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/' | cut -c 2-)
          wget "https://github.com/open-policy-agent/conftest/releases/download/v${LATEST_VERSION}/conftest_${LATEST_VERSION}_Linux_x86_64.tar.gz"
          tar xzf conftest_${LATEST_VERSION}_Linux_x86_64.tar.gz
          sudo mv conftest /usr/local/bin/
          conftest --version
          ls -la
      # - name: docker pull
        # run: |
        #   docker pull openpolicyagent/conftest
      - name: "conf test"
        run: conftest test manifests/Pod.yaml 

#        run: conftest test hello-deply.yaml --policy policy-hello/*
#        run: conftest test hello-deply.yaml --policy policy-hello
#        run: conftest test hello-deply.yaml --policy policy-hello/* 054
#        run: conftest test hello-deply.yaml --policy policy-hello/mypolicy.rego 053

