name: conftest

on:

  workflow_call:
    inputs:
      repository: 
        type: string
      path:
        type: string
    secrets:
      pat:
        required: true

#条件  
jobs:
  import_policy:
    name: conf test
    runs-on: ubuntu-latest
    steps:
      - name: This repository form ci-test
        uses: actions/checkout@v3
      - name: "ls ci-test after checkout"
        run: ls -la  #./policy エラーになる
      - name: rego repository
        uses: actions/checkout@v3
        with:
          repository: ${{ inputs.repository }}
          path: ${{ inputs.path }}
          token: ${{ secrets.pat}} 

      - name: conf install at ci-test
        run: |
          LATEST_VERSION=$(wget -O - "https://api.github.com/repos/open-policy-agent/conftest/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/' | cut -c 2-)
          wget "https://github.com/open-policy-agent/conftest/releases/download/v${LATEST_VERSION}/conftest_${LATEST_VERSION}_Linux_x86_64.tar.gz"
          tar xzf conftest_${LATEST_VERSION}_Linux_x86_64.tar.gz
          sudo mv conftest /usr/local/bin/
          conftest --version
          ls -la
      - name: pwd
        run: pwd
      - name: find yaml-file
        run: |
          yaml_files=`find . -type f | egrep -v 'yobidashi\.yaml$' | egrep '\.(yml|yaml)$'`

          for chk_file in $yaml_files
          do
            conftest test --policy ./policy "$chk_file"
          done

#            conftest test --policy ./policy $chk_file
