name: conftest2

on:
  push:
    branches:
      - develop/conftest

jobs:
  pluto:
    name: conftest-OK
    runs-on: ubuntu-latest
    steps:
      - name: name checkout
      - uses: actions/checkout@v3
      - name: Python3 version
        run: python3 -V
