name: Install Pluto!
on: 
 push:
  branches:
   - develop/pluto 
#  paths:
#   - "test/test.txt"
jobs:
 build:
  name: pluto
  runs-on: ubuntu-latest
  steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Echo
      run: echo "Install Pluto 23"
    
    - name: Pwd echo ls
      run: |
        pwd
        ls -la
        echo "CHK"
        ls -l ./test/test.txt

    - name: Download Pluto
      run: |
        FairwindsOps/pluto/github-action@master

    - name: Use pluto
      run: |
        pluto detect-files -d pkg/finder/testdata

    - name: Check Python3
      run: |
        python3 -V
