name: CI

on:
  push:
    branches:
      - develop/pluto
  pull_request:
    branches:
      - develop/pluto

jobs:
  pluto:
    name: pluto
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download Pluto
        uses: FairwindsOps/pluto/github-action@master
      - name: Use pluto
        run: |
          pluto detect-files -d pkg/finder/testdata