name: pluto install

on:
  push:
    branches:
      - develop/pluto
    paths:
      - 'test/test.txt'

jobs:
  pluto:
    name: pluto install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download Pluto
        uses: FairwindsOps/pluto/github-action@master
      - name: Run Pluto
        run: pluto detect-files -d . -o wide --target-versions k8s=v1.23.0
      - name: Pluto version
        run: pluto version
      - name: Python3 version
        run: python3 -V
