name: pluto test-OK

on:
  push:
    branches:
      - develop/pluto

jobs:
  pluto:
    name: pluto test-OK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download Pluto
        uses: FairwindsOps/pluto/github-action@master
      - name: Run Pluto
        run: pluto detect-files -d . -o wide --target-versions k8s=v1.23.0
      - name: Run serviceaccount.yaml
        run: pluto detect-files -f ./templates/serviceaccount.yaml -o wide --target-versions k8s=v1.23.0
      - name: Pluto version
        run: pluto version
      - name: Python3 version
        run: python3 -V

