name: Install Pluto!
on: 
 push:
  branches:
   - develop/pluto 
  paths:
   - 'text/text.txt'
jobs:
 build:
  name: pluto
  runs-on: ubuntu-latest
  steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Echo
      run: echo "Install Pluto 12"
    
    - name: Pwd echo ls
      run: |
        pwd
        ls -la
        echo "CHK"
        ls -l ./test/text.txt
    - name: Install Pluto
      run: |
        python3 -V
