name: pluto test-OK2

on:
  push:
    branches:
      - develop/pluto

jobs:
  pluto:
    name: pluto test-OK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download Pluto
        uses: FairwindsOps/pluto/github-action@master
      - name: Run test-yaml-file
        run: pluto detect-files -d . 
      - name: Pluto version
        run: pluto version
      - name: Python3 version
        run: python3 -V

