name: validation002

on:

  workflow_call:
    inputs:
      repository: 
        type: string
      path:
        type: string
    secrets:
      pat:
        required: true

#条件  
jobs:
  import_policy:
    name: validation test
    runs-on: ubuntu-latest
    steps:
      - name: 001-repo
        uses: actions/checkout@v3
      - name: "001"
        run: pwd; ls -la
      - name: 002-repo
        uses: actions/checkout@v3
        with:
          repository: ${{ inputs.repository }}
          path: ${{ inputs.path }}
          token: ${{ secrets.pat}} 
      - name: "002"
        run: |
              pwd; ls -la
      - name: "003"
        run: |
              echo "003"
              pwd
              ls -la
              yq eval '.spec.source.helm.value' application.yaml > ./helm_chart_folder/03.values.yaml
              cd ./helm_chart_folder/
              cat 03.values.yaml
              echo 001; pwd; ls -la
              mv values.yaml bk_values.yaml
              mkdir -p charts
              echo 002; pwd; ls -la
              helm version
              helm template -f 03.values.yaml . > 04.testkekka.yaml
              echo 003; pwd; ls -la

#yq eval '.spec.source.helm.value' 02_test.yaml > 03_output.yaml

#pwd; ls -la
#mv application.yaml values.yaml 
#mv application.yaml ./helm_chart_folder/
