name: validation002

on:

  workflow_call:
    inputs:
      repository: 
        type: string
      path:
        type: string
    secrets:
      pat:
        required: true

#条件  
jobs:
  import_policy:
    name: validation test
    runs-on: ubuntu-latest
    steps:
      - name: 001-repo
        uses: actions/checkout@v3
      - name: "001"
        run: pwd; ls -la
      - name: 002-repo
        uses: actions/checkout@v3
        with:
          repository: ${{ inputs.repository }}
          path: ${{ inputs.path }}
          token: ${{ secrets.pat}} 
      - name: "002"
        run: |
              pwd; ls -la
      - name: "003"
        run: |
              echo "003"
              pwd
              ls -la
              mv application.yaml ./helm_chart_folder/
              cd ./helm_chart_folder/
              echo 001; pwd; ls -la
              mv values.yaml bk_values.yaml
              pwd; ls -la
              mv application.yaml values.yaml 
              helm version
              pwd
              helm template . > ./test.yaml
              pwd; ls -la
#